#!/bin/bash

PROPOSE_POINTS=${PROPOSE_POINTS:-10} # 9
MAX_ITERATIONS=${MAX_ITERATIONS:-10} # 3
MAX_BUDGET=${MAX_BUDGET:-110} # 180
DESIGN_SIZE=${DESIGN_SIZE:-10} # 9
PARAM_SET_FILE=${PARAM_SET_FILE:-$WORKFLOW_SETTINGS_FILE} # $EMEWS_PROJECT_ROOT/data/nt3_nightly.R
